### PR TITLE
Fix RSS link in navigation, make subscribing more convenient

### PR DESCRIPTION
**Pull request by hannobraun**
After reading your latest email today, I noticed that I had missed some of your blog posts. I figured I'd fix that problem at its root.

### CODE REVIEW

**Comment by hannobraun** [comment]
I don't understand the CI failure. Please let me know, if there's anything I can do about it. Otherwise, I'll just assume it's not my fault. Docker isn't really my department anyway :-)

**Comment by mre** [comment]
Yeah, so my CI is broken, which is weird. Will look into that.
Thanks for the PR, it makes a lot of sense!
You're the real Dr. McNinja. (Now I can't stop laughing about that comic. 😆)

**Comment by mre** [comment]
No clue. Let's merge it and 🤞. Thanks!

**Comment by mre** [comment]
The live deployment seemed to have worked. So I assume it's broken for pull requests, which makes sense, because I receive very few and never noticed. Will look into that at another time. For now, thanks so much for your PR. Really appreciate it.

**Comment by hannobraun** [comment]
No problem!

> You're the real Dr. McNinja. (Now I can't stop laughing about that comic. :laughing:)

I heard that Dr. McNinja isn't good at computers, but I take it as a compliment anyway :smile:

**Comment by mre** [comment]
In case anyone finds this and has no clue what Hanno is referencing here, go read this comic:
http://drmcninja.com/archives/comic/21p79/
It's perfect. 🤗

**Pull request merged**
